name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  workflow_call:
    inputs:
      releaseVersion:
        description: "New release version"
        required: true
        type: string

jobs:
  show-release-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Show input tag
        id: show-release-tag
        run: |
          echo " ${{ inputs.releaseVersion }}"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build and deploy
        id: generate_next_tag
        run: |
          echo "execute build for ${{ inputs.releaseVersion }}"

