name: Build and deploy

on:
  push:
    branches: [ "master" ]
  workflow_call:
    inputs:
      releaseTag:
        description: "New release version"
        required: true
        type: string
      externalCall:
        description: 'To distinguish workflow_call from regular push'
        type: boolean
        required: false
        default: true  
  workflow_dispatch:
     inputs:
      releaseTag:
        description: "Image name (if empty, the branch name will be used)"
        required: false
        type: string
jobs:
  show-release-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Show input tag
        id: show-release-tag
        run: |
          echo "${{ inputs.releaseVersion }}"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build and deploy
        id: generate_next_tag
        run: |
          VERSION_NAME=${GITHUB_REF_NAME//\//_}
          if [ "${{ inputs.externalCall }}" == "true" ] || [ -n "${{ inputs.releaseTag }}" ]; then
            VERSION_NAME=${{ inputs.releaseTag }}  
          fi
          echo "event name: ${{ github.event_name }}"
          echo "VERSION_NAME: $VERSION_NAME"

