name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: write  # Разрешение на пуш тэгов

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      next_tag: ${{ steps.generate_next_tag.outputs.NEXT_TAG }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get all commits between current branch and main
        id: generate_next_tag
        run: |
          echo "Current branch is ${{ github.ref_name }}"
          
          BRANCH_NAME=${GITHUB_REF_NAME}
          if [[ "$BRANCH_NAME" != release/* ]]; then
              echo "❌ Branch name does not contain 'release'. Exiting..."
              exit 1
          fi
          
          RELEASE_VERSION=$(echo "$BRANCH_NAME" | sed 's/^release\///')
          echo "release version: $RELEASE_VERSION"
          
          TAGS=$(git tag -l "v$RELEASE_VERSION.*")
          echo "Found tags: $TAGS"
          
          LATEST_TAG=$(echo "$TAGS" | sed -E "s/v$RELEASE_VERSION\.([0-9]+)/\1/" | sort -n | tail -n 1)
          LATEST_TAG=${LATEST_TAG:-0} 
          
          NEXT_TAG=$((LATEST_TAG + 1))
          NEXT_TAG="v$RELEASE_VERSION.$NEXT_TAG"
          echo "Next tag: $NEXT_TAG"
          
          echo "NEXT_TAG=$NEXT_TAG" >> $GITHUB_OUTPUT

    # - name: Set up JDK 17
    #   uses: actions/setup-java@v4
    #   with:
    #     java-version: '17'
    #     distribution: 'temurin'
    #     cache: maven
  build-final:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use tag from job1
        run: |
          echo "Current branch is ${{ github.ref_name }}"
          
          echo "Received tag: ${{ needs.build.outputs.next_tag }}"        
          NEXT_TAG=${{ needs.build.outputs.next_tag }}
          git tag "$NEXT_TAG"
          git push origin "$NEXT_TAG"
