name: New build system

on:
  workflow_dispatch:

permissions:
  contents: write  # Разрешение на пуш тэгов

jobs:
  release-build:
    name: Build and deploy release
    uses: ./.github/workflows/maven.yml